---
abstract: 'Core Management and Factory Class for the xclass Ecosystem'
author:
  - 'OnEhIppY @ DomeroSoftware <domerosoftware@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Exception: '0'
  Test::MemoryGrowth: '0'
  Test::More: '0'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'Hand-crafted based on Makefile.PL'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: xclass
requires:
  B::Deparse: '0'
  Benchmark: '0'
  Compress::Zlib: '0'
  Data::MessagePack: '0'
  Devel::Cycle: '0'
  Devel::Size: '0'
  Encode: '0'
  Fcntl: '0'
  File::Temp: '0'
  IO::Handle: '0'
  JSON::XS: '0'
  List::Util: '0'
  Log::Log4perl: '0'
  Scalar::Util: '0'
  Socket: '0'
  Storable: '0'
  Thread::Queue: '0'
  Thread::Semaphore: '0'
  Time::HiRes: '0'
  Try::Tiny: '0'
  Type::Tiny: '0'
  YAML::XS: '0'
  perl: '5.010'
  threads: '0'
  threads::shared: '0'
resources:
  bugtracker: https://github.com/DomeroSoftware/xclass/issues
  repository: https://github.com/DomeroSoftware/xclass.git
version: '2.0.0'
